default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: john
  password:

development:
  <<: *default
  database: stubbing_api_testing_development

test:
  <<: *default
  database: stubbing_api_testing_test
